[pytest]
# Onde o pytest deve procurar os testes por padrão
testpaths = tests

# Ignora as pastas de cache para não poluir os logs
norecursedirs = __pycache__ .pytest_cache

# Configurações padrão do Playwright (Porta padrão do Vite/React)
base_url = http://localhost:5173

# Exibe prints e logs no console se o teste falhar
addopts = -ra -q --tb=short